warp:
  0:
    Material: BEDROCK
    Title: Tp
    Description:
      - multi
      - lign
      - description
    Position: 5
    Command: 
      - tp {PLAYER} 105 71 114
  1:
    Material: MINECART
    Title: lobby
    Description:
      - server lobby
    Position: 3
    Command:
      - \[BungeeCord]send {PLAYER} lobby
lobby:
  0:
    Material: BEDROCK
    Title: send lobby
    Description:
      - send lobby
    Position: 5
    Command:
      - msg {PLAYER} Sending you to lobby
      - \[BungeeCord]send {PLAYER} lobby

